// Auto-generated by scripts/generate-docs-sidebar.js — do not edit manually.
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Skills',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Business Central API Page Generator',
          link: {
            type: 'doc',
            id: 'skills/bc-api-page-generator/SKILL'
          },
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'skills/bc-api-page-generator/references/api-examples',
              label: 'API Page Examples'
            },
            {
              type: 'doc',
              id: 'skills/bc-api-page-generator/references/api-patterns',
              label: 'API Patterns & Best Practices'
            }
          ]
        },
        {
          type: 'category',
          label: 'Business Central API Query Generator',
          link: {
            type: 'doc',
            id: 'skills/bc-api-query-generator/SKILL'
          },
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'skills/bc-api-query-generator/references/query-examples',
              label: 'API Query Examples'
            }
          ]
        },
        {
          type: 'category',
          label: 'BC Attachments, Links & Notes Generator',
          link: {
            type: 'doc',
            id: 'skills/bc-attachments-generator/SKILL'
          },
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'skills/bc-attachments-generator/references/code-templates',
              label: 'BC Attachments Generator - Code Templates'
            }
          ]
        },
        {
          type: 'category',
          label: 'BC Business Events Generator',
          link: {
            type: 'doc',
            id: 'skills/bc-business-events-generator/SKILL'
          },
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'skills/bc-business-events-generator/references/code-templates',
              label: 'Business Events Code Templates'
            }
          ]
        },
        {
          type: 'category',
          label: 'Business Central CDS Page Generator',
          link: {
            type: 'doc',
            id: 'skills/bc-cds-page-generator/SKILL'
          },
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'skills/bc-cds-page-generator/references/examples',
              label: 'CDS Page Generation Examples'
            },
            {
              type: 'doc',
              id: 'skills/bc-cds-page-generator/references/field-layout',
              label: 'CDS Page Field Layout Patterns'
            },
            {
              type: 'doc',
              id: 'skills/bc-cds-page-generator/references/quick-start',
              label: 'Quick Start Guide'
            },
            {
              type: 'doc',
              id: 'skills/bc-cds-page-generator/references/standard-components',
              label: 'Standard Components for CDS List Pages'
            }
          ]
        },
        {
          type: 'category',
          label: 'Business Central Dataverse Entity Generator',
          link: {
            type: 'doc',
            id: 'skills/bc-dataverse-entity-generator/SKILL'
          },
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'skills/bc-dataverse-entity-generator/references/generate-entity-list-script',
              label: 'Generate-Entity-List.ps1 — Full Script Reference'
            },
            {
              type: 'doc',
              id: 'skills/bc-dataverse-entity-generator/references/generate-entity-script',
              label: 'Generate-Entity.ps1 — Full Script Reference'
            },
            {
              type: 'doc',
              id: 'skills/bc-dataverse-entity-generator/references/workflow-examples',
              label: 'Workflow Examples & Troubleshooting'
            }
          ]
        },
        {
          type: 'category',
          label: 'Business Central Dataverse Mapping Generator',
          link: {
            type: 'doc',
            id: 'skills/bc-dataverse-mapping-generator/SKILL'
          },
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'skills/bc-dataverse-mapping-generator/references/custom-entity-mapping',
              label: 'Custom Entity Mapping — Complete Code Reference'
            },
            {
              type: 'doc',
              id: 'skills/bc-dataverse-mapping-generator/references/oob-entity-mapping',
              label: 'OOB Entity Mapping — Extra Field Mappings Reference'
            }
          ]
        },
        {
          type: 'category',
          label: 'Business Central Install Codeunit Generator',
          link: {
            type: 'doc',
            id: 'skills/bc-install-codeunit-generator/SKILL'
          },
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'skills/bc-install-codeunit-generator/references/install-examples',
              label: 'Install Codeunit Examples'
            }
          ]
        },
        {
          type: 'category',
          label: 'Business Central Number Series Generator',
          link: {
            type: 'doc',
            id: 'skills/bc-number-series-generator/SKILL'
          },
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'skills/bc-number-series-generator/references/number-series-examples',
              label: 'Number Series Examples'
            },
            {
              type: 'doc',
              id: 'skills/bc-number-series-generator/references/number-series-troubleshooting',
              label: 'Number Series Troubleshooting'
            }
          ]
        },
        {
          type: 'category',
          label: 'Business Central Setup Table Generator',
          link: {
            type: 'doc',
            id: 'skills/bc-setup-table-generator/SKILL'
          },
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'skills/bc-setup-table-generator/references/patterns',
              label: 'Advanced Setup Table Patterns'
            }
          ]
        },
        {
          type: 'category',
          label: 'BC Setup Wizard Generator',
          link: {
            type: 'doc',
            id: 'skills/bc-setup-wizard-generator/SKILL'
          },
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'skills/bc-setup-wizard-generator/references/code-templates',
              label: 'BC Setup Wizard - Code Templates'
            }
          ]
        },
        {
          type: 'category',
          label: 'BC Telemetry Generator',
          link: {
            type: 'doc',
            id: 'skills/bc-telemetry-generator/SKILL'
          },
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'skills/bc-telemetry-generator/references/kql-queries',
              label: 'KQL Queries for Application Insights'
            },
            {
              type: 'doc',
              id: 'skills/bc-telemetry-generator/references/telemetry-reference',
              label: 'Telemetry Reference Patterns'
            }
          ]
        },
        {
          type: 'category',
          label: 'Business Central Test Codeunit Generator',
          link: {
            type: 'doc',
            id: 'skills/bc-test-codeunit-generator/SKILL'
          },
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'skills/bc-test-codeunit-generator/references/test-examples',
              label: 'Test Codeunit Examples'
            }
          ]
        },
        {
          type: 'category',
          label: 'Business Central Upgrade Codeunit Generator',
          link: {
            type: 'doc',
            id: 'skills/bc-upgrade-codeunit-generator/SKILL'
          },
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'skills/bc-upgrade-codeunit-generator/references/upgrade-examples',
              label: 'Upgrade Codeunit Examples'
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Instructions',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'instructions/skills-creation.instructions',
          label: 'Custom Skills Creation Guidelines'
        }
      ]
    },
    {
      type: 'category',
      label: 'Release Notes',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '2026',
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'releasenotes/2026/april',
              label: 'April 2026'
            }
          ]
        }
      ]
    },
    'contributing',
    'SECURITY',
    'LICENSE'
  ]
};

export default sidebars;
