// Auto-generated by scripts/generate-skills-sidebar.js — do not edit manually.
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsSkills: SidebarsConfig = {
  skillsSidebar: [
    {
        type: 'doc',
        id: 'overview',
        label: 'Skills Overview'
    },
    {
        type: 'category',
        label: 'Business Central API Page Generator',
        link: {
            type: 'doc',
            id: 'bc-api-page-generator/SKILL'
        },
        collapsed: true,
        items: [
            {
                type: 'doc',
                id: 'bc-api-page-generator/references/api-examples',
                label: 'API Page Examples'
            },
            {
                type: 'doc',
                id: 'bc-api-page-generator/references/api-patterns',
                label: 'API Patterns & Best Practices'
            }
        ]
    },
    {
        type: 'category',
        label: 'Business Central API Query Generator',
        link: {
            type: 'doc',
            id: 'bc-api-query-generator/SKILL'
        },
        collapsed: true,
        items: [
            {
                type: 'doc',
                id: 'bc-api-query-generator/references/query-examples',
                label: 'API Query Examples'
            }
        ]
    },
    {
        type: 'category',
        label: 'BC Attachments, Links & Notes Generator',
        link: {
            type: 'doc',
            id: 'bc-attachments-generator/SKILL'
        },
        collapsed: true,
        items: [
            {
                type: 'doc',
                id: 'bc-attachments-generator/references/code-templates',
                label: 'BC Attachments Generator - Code Templates'
            }
        ]
    },
    {
        type: 'category',
        label: 'BC Business Events Generator',
        link: {
            type: 'doc',
            id: 'bc-business-events-generator/SKILL'
        },
        collapsed: true,
        items: [
            {
                type: 'doc',
                id: 'bc-business-events-generator/references/code-templates',
                label: 'Business Events Code Templates'
            }
        ]
    },
    {
        type: 'category',
        label: 'Business Central CDS Page Generator',
        link: {
            type: 'doc',
            id: 'bc-cds-page-generator/SKILL'
        },
        collapsed: true,
        items: [
            {
                type: 'doc',
                id: 'bc-cds-page-generator/references/examples',
                label: 'CDS Page Generation Examples'
            },
            {
                type: 'doc',
                id: 'bc-cds-page-generator/references/field-layout',
                label: 'CDS Page Field Layout Patterns'
            },
            {
                type: 'doc',
                id: 'bc-cds-page-generator/references/quick-start',
                label: 'Quick Start Guide'
            },
            {
                type: 'doc',
                id: 'bc-cds-page-generator/references/standard-components',
                label: 'Standard Components for CDS List Pages'
            }
        ]
    },
    {
        type: 'category',
        label: 'Business Central Dataverse Entity Generator',
        link: {
            type: 'doc',
            id: 'bc-dataverse-entity-generator/SKILL'
        },
        collapsed: true,
        items: [
            {
                type: 'doc',
                id: 'bc-dataverse-entity-generator/references/generate-entity-list-script',
                label: 'Generate-Entity-List.ps1 — Full Script Reference'
            },
            {
                type: 'doc',
                id: 'bc-dataverse-entity-generator/references/generate-entity-script',
                label: 'Generate-Entity.ps1 — Full Script Reference'
            },
            {
                type: 'doc',
                id: 'bc-dataverse-entity-generator/references/workflow-examples',
                label: 'Workflow Examples & Troubleshooting'
            }
        ]
    },
    {
        type: 'category',
        label: 'Business Central Dataverse Mapping Generator',
        link: {
            type: 'doc',
            id: 'bc-dataverse-mapping-generator/SKILL'
        },
        collapsed: true,
        items: [
            {
                type: 'doc',
                id: 'bc-dataverse-mapping-generator/references/custom-entity-mapping',
                label: 'Custom Entity Mapping — Complete Code Reference'
            },
            {
                type: 'doc',
                id: 'bc-dataverse-mapping-generator/references/oob-entity-mapping',
                label: 'OOB Entity Mapping — Extra Field Mappings Reference'
            }
        ]
    },
    {
        type: 'category',
        label: 'Business Central Install Codeunit Generator',
        link: {
            type: 'doc',
            id: 'bc-install-codeunit-generator/SKILL'
        },
        collapsed: true,
        items: [
            {
                type: 'doc',
                id: 'bc-install-codeunit-generator/references/install-examples',
                label: 'Install Codeunit Examples'
            }
        ]
    },
    {
        type: 'category',
        label: 'Business Central Number Series Generator',
        link: {
            type: 'doc',
            id: 'bc-number-series-generator/SKILL'
        },
        collapsed: true,
        items: [
            {
                type: 'doc',
                id: 'bc-number-series-generator/references/number-series-examples',
                label: 'Number Series Examples'
            },
            {
                type: 'doc',
                id: 'bc-number-series-generator/references/number-series-troubleshooting',
                label: 'Number Series Troubleshooting'
            }
        ]
    },
    {
        type: 'category',
        label: 'Business Central Setup Table Generator',
        link: {
            type: 'doc',
            id: 'bc-setup-table-generator/SKILL'
        },
        collapsed: true,
        items: [
            {
                type: 'doc',
                id: 'bc-setup-table-generator/references/patterns',
                label: 'Advanced Setup Table Patterns'
            }
        ]
    },
    {
        type: 'category',
        label: 'BC Setup Wizard Generator',
        link: {
            type: 'doc',
            id: 'bc-setup-wizard-generator/SKILL'
        },
        collapsed: true,
        items: [
            {
                type: 'doc',
                id: 'bc-setup-wizard-generator/references/code-templates',
                label: 'BC Setup Wizard - Code Templates'
            }
        ]
    },
    {
        type: 'category',
        label: 'BC Telemetry Generator',
        link: {
            type: 'doc',
            id: 'bc-telemetry-generator/SKILL'
        },
        collapsed: true,
        items: [
            {
                type: 'doc',
                id: 'bc-telemetry-generator/references/kql-queries',
                label: 'KQL Queries for Application Insights'
            },
            {
                type: 'doc',
                id: 'bc-telemetry-generator/references/telemetry-reference',
                label: 'Telemetry Reference Patterns'
            }
        ]
    },
    {
        type: 'category',
        label: 'Business Central Test Codeunit Generator',
        link: {
            type: 'doc',
            id: 'bc-test-codeunit-generator/SKILL'
        },
        collapsed: true,
        items: [
            {
                type: 'doc',
                id: 'bc-test-codeunit-generator/references/test-examples',
                label: 'Test Codeunit Examples'
            }
        ]
    },
    {
        type: 'category',
        label: 'Business Central Upgrade Codeunit Generator',
        link: {
            type: 'doc',
            id: 'bc-upgrade-codeunit-generator/SKILL'
        },
        collapsed: true,
        items: [
            {
                type: 'doc',
                id: 'bc-upgrade-codeunit-generator/references/upgrade-examples',
                label: 'Upgrade Codeunit Examples'
            }
        ]
    }
],
};

export default sidebarsSkills;
